メニュー追加、コンソール入力実装
watanabemasao/Kadai0502 pull request #2
Opened 2022-05-29 16:37 UTC by watanabemasao

2022-05-29 18:39 UTC, yoshi-koyama commented on src/main/java/CustomerList.java
> +        return new ArrayList<>(List.of(no0));
![badge](https://img.shields.io/badge/review-imo-orange.svg)
```suggestion
        Collections.singletonList(new CustomerForm(scannerAge, scannerName, scannerGender));
```

2022-05-30 02:11 UTC, YudaiNoda3576 requested changes

2022-05-30 02:11 UTC, YudaiNoda3576 commented on src/main/java/Main.java
> +}
改行ですね〜！
PR出す前にチェックする習慣をつけるのがおすすめです！
こういうレビューはレビューされる側もただ落ち込むだけだと思うので笑
自分で気づいて先に修正できるようになると成長を実感できるのでおすすめです:smile:

2022-05-30 03:50 UTC, yoshi-koyama commented on src/main/java/CustomerList.java
> +    private static String scannerGender;
static変数にする意味はあまりないのかなと感じます。
どちらかというと
```java
private List<CustomerForm> customerFormList;
```
のようにListをフィールド変数にもたせたいです。

またstaticのつかいどころは授業では触れていません（難易度がやや高いため）。
が、「状態をもたせる」のはよくありません。

20行目の`setScannerAge`もですね。
`java static メソッド 使い方`
`static method how to use`
などで調べてみてください。

どう直していいかわからなければ聞いてください 👍

2022-05-30 03:50 UTC, yoshi-koyama commented on src/main/java/Main.java
> +        CustomerList.setScannerGender(scannerGender);
CustomerListはインスタンス化して、ユーザーの入力値をコンストラクタで渡すようにしたい。

イメージは
```java
CustomerList customerList = new CustomerList(scannerAge, scanner Name, scannerGender);
```

2022-05-30 03:50 UTC, yoshi-koyama commented on src/main/java/Main.java
> +                customerList().get(0)));
![badge](https://img.shields.io/badge/nits-imo-green.svg)
```suggestion
        System.out.println(CinemaPricing.cinemaInfo(CustomerList.customerList().get(0)));
```

2022-06-02 15:40 UTC, yoshi-koyama approved these changes
修正確認しました！

LGTMです。

2022-06-02 16:32 UTC, merged